//
// Created by Niklas Arnitz on 11.11.24.
//

#ifndef BREWPILOT_GROUPHEADERSTATE_H
#define BREWPILOT_GROUPHEADERSTATE_H

enum GroupHeadState {
    GROUP_HEAD_IDLE,
    GROUP_HEAD_EXTRACTING
};

#endif //BREWPILOT_GROUPHEADERSTATE_H
