//
// Created by Niklas Arnitz on 16.11.24.
//

#ifndef BREWPILOT_GROUPHEADBUTTONEVENT_H
#define BREWPILOT_GROUPHEADBUTTONEVENT_H

enum class GroupHeadButtonEvent
{
    LEFT_SINGLE_ESPRESSO,
    LEFT_DOUBLE_ESPRESSO,
    RIGHT_SINGLE_ESPRESSO,
    RIGHT_DOUBLE_ESPRESSO,
    CONTINUOUS,
    CONTINUOUS_HELD,
    AUTO_BACKFLUSH,
    NONE
};

#endif // BREWPILOT_GROUPHEADBUTTONEVENT_H
