//
// Created by Niklas Arnitz on 11.11.24.
//

#ifndef BREWPILOT_CONFIG_H
#define BREWPILOT_CONFIG_H

#define DEBUG true

// Pins
// Outputs
#define PUMP_RELAY_PIN 1
#define BOILER_PROBE_PIN 2
#define BOILER_FILL_VALVE_PIN 3
#define GROUP_ONE_FLOW_METER_PIN 4
#define GROUP_TWO_FLOW_METER_PIN 5
#define GROUP_ONE_SOLENOID_PIN 6
#define GROUP_TWO_SOLENOID_PIN 7
#define TEA_WATER_SOLENOID_PIN 8
#define TEA_WATER_EXTRACTION_SOLENOID_PIN 9

// Inputs
#define IN_GROUP_ONE_BIG_DRINKS 13
#define IN_GROUP_ONE_SMALL_DRINKS 12
#define IN_GROUP_ONE_STOP 14

#define IN_GROUP_LEFT_BIG_DRINKS 27
#define IN_GROUP_LEFT_SMALL_DRINKS 26
#define IN_GROUP_LEFT_STOP 25

#define OUT_GROUP_LEFT_LEFT_HALF_AND_STOP 33
#define OUT_GROUP_LEFT_RIGHT_HALF 32

#define OUT_TEA_WATER 19

#define OUT_GROUP_RIGHT_LEFT_HALF_AND_STOP 21
#define OUT_GROUP_RIGHT_RIGHT_HALF 22

#define IN_TEA_WATER 23

// Boiler Stuff
// TODO: TEST THIS
#define BOILER_FILL_LEVEL 100

#endif // BREWPILOT_CONFIG_H
